### ISSUE TITLE
Thanks For such wonderfull project ! 

### ISSUE THREAD

**Issue by Decapitater** [twpayne/dotfiles#2]
### i know this is lame but i have some questions.

- i have seen people separate files while using chezmoi , in my case it tries to keep them all in private_dot_files & i separate them out will chezmoi still be able to manage them without breaking symlinks ? 
-  How do you (Personally ) like to manage the dotfile changes ?

I would love to contribute @twpayne in development , alas the day i learn to code

**Comment by twpayne** [comment]
Thanks for the kind words. Please ask questions in the chezmoi repo.
